version: 0.0
os: linux
files:
  - source: /
    destination: /home/node/public_html   
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: node
    group: node
    
hooks:
  AfterInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

